#ifndef game_h
#define game_h
#include <string>

using std::string;

class Game {
public:
  Game(const char* plyName, int nFeatures);
  virtual ~Game();

  virtual void startGame();

protected:
  const int     n_features_;  // N value
  const int     m_srv_cand_;  // M value(Num of exact W candidates generated by srv)
  const string  ply_name_;  // Player I am in control
  double*       w_arr_;  // weight vector from Person
  double**      xx_matr_;  // M candidates generated by srv

private:
};

#endif  // game_h
